theme: jekyll-theme-minimal
title: Joseph C. Sheils
description: I am currently a research assistant in the Rational Intelligence Lab at CISPA Helmholtz Center for Information Security, and a master's student at Universität des Saarlandes.


