theme: jekyll-theme-minimal
title: Joseph C. Sheils
description: I am currently a Junior Researcher in the Smart Energy Lab at the August-Wilhelm Scheer Institut, and a master's student in Data Science and Artificial Intelligence at Universität des Saarlandes.


